name: recsys_tf2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.12
  - pip
  - pip:
    - tensorflow>=2.12.0,<2.15
    - polars
    - pandas
    - scikit-learn
    - debugpy
