name: recsys_tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.11
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - numpy<2
    - tensorflow<2.11
    - polars
    - pandas
    - scikit-learn
    - debugpy
