name: recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=23.3.1
  - pip:
    - tensorflow>=1.15,<2.0
    - polars
    - pandas
    - protobuf==3.20.*
    - scikit-learn
    - debugpy
